name: Push

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  buildjbrowseweb-development:
    name: Build jbrowse-web in development mode
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 2
          persist-credentials: false
      - name: Get latest release tag
        id: latest_release
        run: |
          git remote add GMOD https://github.com/GMOD/jbrowse-components.git || true
          git fetch --tags GMOD
          latest_release=$( \
            git tag --merged HEAD | \
            grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | \
            sort -V | \
            tail -n 1 \
          )
          echo "Lastest release: $latest_release"
          echo "tag=$latest_release" >> $GITHUB_OUTPUT
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 10
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build jbrowse-web
        run: |
          echo $RELEASE_VERSION
          cd products/jbrowse-web/
          NODE_OPTIONS='--max-old-space-size=6500' pnpm build
          cd build && zip -r "jbrowse-web-${{steps.latest_release.outputs.tag}}.zip" .

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{steps.latest_release.outputs.tag}}-dev
          name: Dev Build ${{steps.latest_release.outputs.tag}}
          files: products/jbrowse-web/build/jbrowse-web-${{steps.latest_release.outputs.tag}}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
