name: Push

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  buildjbrowseweb-development:
    name: Build jbrowse-web in development mode
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 2
          persist-credentials: false
      - name: Get latest release tag
        id: latest_release
        run: |
          git remote add GMOD https://github.com/GMOD/jbrowse-components.git || true
          git fetch --tags GMOD
          latest_release=$( \
            git tag --merged HEAD | \
            grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | \
            sort -V | \
            tail -n 1 \
          )
          echo "Lastest release: $latest_release"
          echo "tag=$latest_release" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: '22'
      - name: Install deps (with cache)
        uses: bahmutov/npm-install@3714964fb879ebbbc108e167f0f3a0c81ec075c9 # v1.10.10
      - name: Build project
        run: |
          echo $RELEASE_VERSION
          cd products/jbrowse-web/
          NODE_OPTIONS='--max-old-space-size=6500' yarn build
          cd ../../
      - name: Prepare zip file
        run: |
          cd products/jbrowse-web/build
          zip -r "jbrowse-web-${{steps.latest_release.outputs.tag}}.zip" .
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{steps.latest_release.outputs.tag}}-dev
          name: Dev Build ${{steps.latest_release.outputs.tag}}
          files: products/jbrowse-web/build/jbrowse-web-${{steps.latest_release.outputs.tag}}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
